on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for opening an issue, we combe back shortly.'
            })
      - name: Notify
        run: echo ${{ github.event.issue.url }} ${{ secrets.SLACK_WEBHOOK}}

      - name: Notify
        run: ~/.github/notify.sh ${{ github.event.issue.title }} ${{ github.event.issue.url }} ${{ secrets.SLACK_WEBHOOK}}
