on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for opening an issue, we combe back shortly.'
            })
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ secrets.SLACK_WEBHOOK}}
          ISSUE_TITLE: ${{ context.issue.titl }}
          ISSUE_URL: ${{ context.issue.url }}
        run: .github/notify.sh
