name: build1
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual mode"
        required: true
        default: "test run..."

jobs:
  cowsay1_1:
    runs-on: self-hosted
    container: npalm/cowsay

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cowsay -f ghostbusters "   Who ya gonna call?" > cow.txt
          cat cow.txt

  cowsay1_2:
    runs-on: self-hosted
    container: npalm/cowsay

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cowsay -f ghostbusters "   Who ya gonna call?" > cow.txt
          cat cow.txt
