name: build2
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual mode 2"
        required: true
        default: "test run..."

jobs:
  cowsay2_1:
    runs-on: self-hosted
    container: npalm/cowsay

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cowsay -f ghostbusters "   Who ya gonna call?" > cow.txt
          cat cow.txt

  cowsay2_2:
    runs-on: self-hosted
    container: npalm/cowsay
    needs: cowsay1

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cowsay -f ghostbusters "   Who ya gonna call?" > cow.txt
          cat cow.txt
